//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.B2B.eTendering.Website.Account {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new GARMCO.AMS.B2B.eTendering.Website.CommonObject.Site Master {
            get {
                return ((GARMCO.AMS.B2B.eTendering.Website.CommonObject.Site)(base.Master));
            }
        }
    }
}
