using System;

namespace GARMCO.AMS.B2B.Admin.DAL
{
    public class StockItem
    {
        public string StockABCClass1 { get; set; }
        public string StockABCClass2 { get; set; }
        public string StockABCClass3 { get; set; }
        public double StockAvePOLeadTime { get; set; }
        public double StockAvgIntIssuedDay { get; set; }
        public string StockDesc { get; set; }
        public string StockDrawingNo { get; set; }
        public byte[] StockExtDesc { get; set; }
        public string StockGLCategory { get; set; }
        public string StockGLCategoryDesc { get; set; }
        public double StockIssued01 { get; set; }
        public double StockIssued02 { get; set; }
        public double StockIssued03 { get; set; }
        public double StockIssued04 { get; set; }
        public double StockIssued05 { get; set; }
        public double StockIssued06 { get; set; }
        public double StockIssued07 { get; set; }
        public double StockIssued08 { get; set; }
        public double StockIssued09 { get; set; }
        public double StockIssued10 { get; set; }
        public double StockIssued11 { get; set; }
        public double StockIssued12 { get; set; }
        public double StockIssuedYTD { get; set; }
        public string StockItemNo { get; set; }
        public DateTime StockLastDateUpdated { get; set; }
        public double StockNoIntIssued { get; set; }
        public string StockObjectAcct { get; set; }
        public double StockOnHand { get; set; }
        public double StockOnHandPrimary { get; set; }
        public double StockOutstandingPO { get; set; }
        public double StockOutstandingPR { get; set; }
        public double StockPOBuyer1 { get; set; }
        public double StockPOBuyer2 { get; set; }
        public double StockPOBuyer3 { get; set; }
        public double StockPOBuyer4 { get; set; }
        public double StockPOBuyer5 { get; set; }
        public DateTime? StockPODateCreated1 { get; set; }
        public DateTime? StockPODateCreated2 { get; set; }
        public DateTime? StockPODateCreated3 { get; set; }
        public DateTime? StockPODateCreated4 { get; set; }
        public DateTime? StockPODateCreated5 { get; set; }
        public double StockPODocNo1 { get; set; }
        public double StockPODocNo2 { get; set; }
        public double StockPODocNo3 { get; set; }
        public double StockPODocNo4 { get; set; }
        public double StockPODocNo5 { get; set; }
        public double StockPOLeadTime1 { get; set; }
        public double StockPOLeadTime2 { get; set; }
        public double StockPOLeadTime3 { get; set; }
        public double StockPOLeadTime4 { get; set; }
        public double StockPOLeadTime5 { get; set; }
        public string StockPOSupplierName1 { get; set; }
        public string StockPOSupplierName2 { get; set; }
        public string StockPOSupplierName3 { get; set; }
        public string StockPOSupplierName4 { get; set; }
        public string StockPOSupplierName5 { get; set; }
        public double StockPOSupplierNo1 { get; set; }
        public double StockPOSupplierNo2 { get; set; }
        public double StockPOSupplierNo3 { get; set; }
        public double StockPOSupplierNo4 { get; set; }
        public double StockPOSupplierNo5 { get; set; }
        public double StockPOUnitCost1 { get; set; }
        public double StockPOUnitCost2 { get; set; }
        public double StockPOUnitCost3 { get; set; }
        public double StockPOUnitCost4 { get; set; }
        public double StockPOUnitCost5 { get; set; }
        public double StockPrevIssued01 { get; set; }
        public double StockPrevIssued02 { get; set; }
        public double StockPrevIssued03 { get; set; }
        public double StockPrevIssued04 { get; set; }
        public double StockPrevIssued05 { get; set; }
        public double StockPrevIssued06 { get; set; }
        public double StockPrevIssued07 { get; set; }
        public double StockPrevIssued08 { get; set; }
        public double StockPrevIssued09 { get; set; }
        public double StockPrevIssued10 { get; set; }
        public double StockPrevIssued11 { get; set; }
        public double StockPrevIssued12 { get; set; }
        public string StockPrimaryLoc { get; set; }
        public double StockQtyDailyUtilization { get; set; }
        public double StockQuantityPO { get; set; }
        public double StockQuantityPR { get; set; }
        public double StockReorderPt { get; set; }
        public double StockReorderQuantity { get; set; }
        public string StockRevisionNo { get; set; }
        public double StockSafety { get; set; }
        public double StockShelfLifeDays { get; set; }
        public double StockShortItemNo { get; set; }
        public string StockSubsidiary { get; set; }
        public string StockType { get; set; }
        public string StockTypeDesc { get; set; }
        public string StockUM { get; set; }
        public string StockUMDesc { get; set; }
    }
}